# Generated by Django 5.2.6 on 2026-09-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='logo',
            new_name='image',
        ),
    ]
