# Generated by Django 5.2.6 on 2026-09-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_logo_skills_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.ImageField(upload_to='profilepic')),
                ('second', models.ImageField(upload_to='profilepic')),
                ('third', models.ImageField(upload_to='profilepic')),
            ],
            options={
                'verbose_name': 'Profile Image',
                'verbose_name_plural': 'Profile Images ',
            },
        ),
    ]
