# Generated by Django 5.2.6 on 2026-09-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profileimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='project image', upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(upload_to='skills_images'),
        ),
    ]
